### ISSUE TITLE
Антон Белый, 2539

### ISSUE THREAD

**Issue by AVBelyy** [itmoasm2015/Homework2#1]
2539/Belyy

**Comment by imihajlow** [comment]
Код 7/8, комментарии 7/7, бонус 4 (сдал первым).

За что минус балл: в строчке 340 вы используете абсолютную адресацию. В 64-битном коде лучше использовать RIP-относительную адресацию (использовать _rel_ в адресе или директиву _default rel_ в начале файла). При абсолютной адресации смещения задаются 32-битными числами, поэтому теоретически возможен случай, когда линкер вообще не сможет разместить такую программу (если данные окажутся по адресам больше 2^32). Объектный формат Mach-O, например, вообще не поддерживает абсолютные адреса для 64-битного кода.

Да и константу в памяти совсем не нужно хранить, можно использовать _xorps_ для обнуления регистра.
