### ISSUE TITLE
Sugak Andrey, 2536

### ISSUE THREAD

**Issue by sugakandrey** [itmoasm2015/Homework2#10]

**Comment by imihajlow** [comment]
Segmentation fault, если пытаться складывать матрицы разного размера.

**Comment by sugakandrey** [comment]
Пофиксил.

**Comment by imihajlow** [comment]
Код 7/8, комментарии 7/7.
Замечание: ваша `matrixClone` не удовлетворяет конвенции вызова — не сохраняет `rbx`. Программист, обнаруживший такую недокументированную функцию (а она доступна наружу) и решивший ее использовать, может быть неприятно удивлен падением программы в самый неподходящий момент.
