### ISSUE TITLE
Бережко Герман, 2538

### ISSUE THREAD

**Issue by gerra** [itmoasm2015/Homework2#11]
2538/berezhko

**Comment by imihajlow** [comment]
`matrixMul` не сохраняет r13, r14, r15. См. http://en.wikipedia.org/wiki/X86_calling_conventions#System_V_AMD64_ABI

**Comment by gerra** [comment]
Спасибо. Надеюсь, только в этом косяк. Исправил.

**Comment by imihajlow** [comment]
Код 6/8, комментарии 7/7.

Не нужно вызывать в коде маленькие функции вроде `matrixGetCols`. Расход времени на вызов такой функции гораздо больше, чем на ее полезную работу. Для повышения читаемости можно перенести их код в макрос, который использовать уже везде (как у вас сделано с `roundToFour`). Даже `matrixGet` возможно стоит переделать в макрос. Компилятор при высоких уровнях оптимизации автоматически делает такую работу по встраиванию кода, но при программировании на ассемблере приходится думать об этом самостоятельно.
