### ISSUE TITLE
Del

### ISSUE THREAD

**Issue by ftk** [itmoasm2015/Homework2#14]
Del

**Comment by imihajlow** [comment]
VirtualBox не может AVX, а в OS X возникает ошибка невыровненного стека при вызове `malloc`. Согласно конвенции вызова, стек должен быть выровнен на 16 байт перед вызовом функции. Linux не следит за этим, а для OS X это оказалось критичным. Пожалуйста, выровняйте стек.

**Comment by ftk** [comment]
Исправлено

**Comment by imihajlow** [comment]
Нет, не исправлено. В функции `memalign32` перед вызовом `malloc` RSP = 8 (mod 16).

**Comment by ftk** [comment]
Действительно, забыл, что call изменяет rsp. Сейчас вроде исправил.

**Comment by imihajlow** [comment]
Код 8/8, комментарии 5/7, бонус 5 баллов за AVX и разворачивание циклов.
