### ISSUE TITLE
Яковлева Дарья, 2539

### ISSUE THREAD

**Issue by DariaYakovleva** [itmoasm2015/Homework2#16]
https://github.com/itmoasm2015/Homework2/tree/master/2539/Yakovleva

**Comment by imihajlow** [comment]
`matrixNew` не заполняет матрицу нулями. Читайте внимательнее условие.

**Comment by DariaYakovleva** [comment]
fixed. Forget about it, sorry

**Comment by imihajlow** [comment]
Не волнуйтесь, Дарья! И `git push` сделать не забудьте, а то кода нового нет.

**Comment by DariaYakovleva** [comment]
Done:)
Пт, 3 апр. 2015 г. в 20:25, Ivan Mikhaylov notifications@github.com:

**Comment by DariaYakovleva** [comment]
Done:)

**Comment by DariaYakovleva** [comment]
I have done it(

**Comment by imihajlow** [comment]
Код 5/8, комментарии 7/7.

Вы сохраняете лишние регистры. Конечно, от этого корректность программы не страдает, но это просто лишняя работа.

Еще для улучшения читаемости можно было добавить константы, которые обозначают смещение полей в структуре или вообще использовать директиву `struc`, как сделали некоторые.

Кроме того, вместо умножения на степени двойки намного эффективнее использовать сдвиг влево. Впрочем, в вашем коде это может быть важно только внутри `matrixGet` и `matrixSet`, которые могут извне вызываться много раз в цикле.

И вместо копирования кода нужно было применять макросы.

**Comment by DariaYakovleva** [comment]
Но я сохраняла лишние регистры потому что Malloc их портит(

**Comment by imihajlow** [comment]
Конвенция вызова определяет, что вызываемая функция должна сохранять только RBX, RBP, R12-R15, а остальные она вправе портить.

**Comment by DariaYakovleva** [comment]
Поняла
Пт, 3 апр. 2015 г. в 22:46, Ivan Mikhaylov notifications@github.com:
