### ISSUE TITLE
Скорость программ

### ISSUE THREAD

**Issue by knah** [itmoasm2015/Homework2#2]
Есть интересная идея: почему бы не оценивать не только корректность, но и скорость кода, и давать бонусы авторам самых быстрых программ из сдавших вовремя?
Одна из основных причин для использования ассемблера - увеличение скорости работы программы. Было бы приятно иметь дополнительную мотивацию для написания быстрого кода. 
К тому же, в подобном действе могут быть заинтересованы и другие студенты.

**Comment by imihajlow** [comment]
Идея отличная, я обязательно проведу соревнование по скорости программ.

**Comment by dimatomp** [comment]
Лишь одна проблема - не у всех людей есть расширение, скажем, AVX. Эту проблему они наверняка могут решить, но всё же условия не совсем равные.
