### ISSUE TITLE
Muratov Amir, 2539

### ISSUE THREAD

**Issue by AmirMuratov** [itmoasm2015/Homework2#20]

**Comment by imihajlow** [comment]
Неправильно работает умножение на скаляр.

**Comment by AmirMuratov** [comment]
Исправил.

**Comment by imihajlow** [comment]
Segmentation fault.

**Comment by AmirMuratov** [comment]
Если это была ошибка из-за того, что умножение не возвращало 0, то я ее исправил.

**Comment by imihajlow** [comment]
Код 6/8, комментарии 6/7.
