### ISSUE TITLE
Филиппов Дмитрий, 2539

### ISSUE THREAD

**Issue by DimaPhil** [itmoasm2015/Homework2#26]
2539/Filippov

**Comment by imihajlow** [comment]
Умножение неправильно работает.

**Comment by DimaPhil** [comment]
А не подскажете, что именно не работает? Мои рандомные тесты проходят

2015-04-05 17:17 GMT+03:00 Ivan Mikhaylov notifications@github.com:

**Comment by imihajlow** [comment]
Да просто неправильно считает.

**Comment by DimaPhil** [comment]
Я вроде уже проверил на всем, чем можно
Взял тесты других ребят, запустил на них, тоже работает
Не знаю, в чем проблема :(

**Comment by DimaPhil** [comment]
"Если размеры матрицы не позволяют их перемножить, то функция должна вернуть 0" -- это значит, что перемножение очень больших матриц тоже должно возвращать 0?

**Comment by imihajlow** [comment]
Умножение таких больших матриц, которые не влезут в память, не проверяется. А вообще да.

Проверьте матрицы разного размера. У вас падает на m1=20x38, m2=38x40. В моем тесте матрицы заполняются случайными числами. Проверьте также, что данные в исходных матрицах не портятся.

**Comment by DimaPhil** [comment]
Да, точно, меняются исходные матрицы. Точнее, вторая из них просто удаляется (я случайно :) )
Поправил, теперь запуск функции два раза подряд работает, все сохраняется

**Comment by imihajlow** [comment]
Код 7, комментарии 7.
