### ISSUE TITLE
Timofeev Kirill, 2536

### ISSUE THREAD

**Issue by KirillTim** [itmoasm2015/Homework2#29]

**Comment by imihajlow** [comment]
Умножение не работает.

**Comment by KirillTim** [comment]
как именно не работает? выдаёт не верный результат?

**Comment by imihajlow** [comment]
Да. А еще, видимо, портит стек, так что программа вылетает.

**Comment by KirillTim** [comment]
исправил

**Comment by imihajlow** [comment]
Код 7, комментарии 7.
