### ISSUE TITLE
Королева Яна, 2538

### ISSUE THREAD

**Issue by KorolevaYana** [itmoasm2015/Homework2#30]
2538/Koroleva

**Comment by imihajlow** [comment]
`matrixGet` возвращает не те значения, которые переданы в `matrixSet`.

**Comment by KorolevaYana** [comment]
Fixed.

**Comment by imihajlow** [comment]
Теперь умножение не работает.

**Comment by KorolevaYana** [comment]
Fixed.

**Comment by imihajlow** [comment]
Код 7, комментарии 6.

Табы зло.

**Comment by loskutov** [comment]
Табы — концентрированное добро!

**Comment by knah** [comment]
Табы - добро ровно до тех пор, пока они не находятся в соседстве с пробелами.

**Comment by loskutov** [comment]
Ну да, за исключением случая, когда табами отступ, а пробелами — выравнивание относительно него.

**Comment by imihajlow** [comment]
Можете открыть код Яны прямо здесь, на гитхабе, и посмотреть, как всё поехало. А всё потому, что здесь 8 символов на таб, а рассчитано было на 4 или даже на 2.

**Comment by loskutov** [comment]
Да, это я просто из любви к срачам в комментах.
