### ISSUE TITLE
Химуля Александр, 2537

### ISSUE THREAD

**Issue by viscount-sanchez** [itmoasm2015/Homework2#4]

**Comment by imihajlow** [comment]
Не компилируется без boost (make по умолчанию должен делать только libhw.a, а если делает еще что-то, то не падать).
А еще:

```
hwmatrices.asm:93: warning: value does not fit in 32 bit field
```

**Comment by viscount-sanchez** [comment]
Теперь компилируется без boost.
Предупреждение крайне странное: не вижу проблем сделать and 64-битного регистра и 64-битной константы. Заменил константу на отрицательное значение с аналогичным дополнительным кодом.

**Comment by imihajlow** [comment]
Не бывает инструкции AND с 64-битной константой. А вот MOV бывает.

А еще у вас ошибка: умножение выдает матрицу неправильного размера. Может быть, перепутаны строки и столбцы?

**Comment by viscount-sanchez** [comment]
Исправлено.

**Comment by imihajlow** [comment]
http://en.wikipedia.org/wiki/X86_calling_conventions#System_V_AMD64_ABI
R8 и R9 сохранять не нужно, в них идут параметры.

Вместо некоторых функций (alignToFour, getAddress) лучше было использовать макросы.
Кроме того, не стоит вызывать внутри кода простые функции вроде matrixGetCols. Слишком много лишней работы на вызов функции по сравнению с ее содержимым в одну инструкцию. Если хочется повысить читаемость, то опять же можно сделать макрос.

Не написано, как хранится матрица.

Код 5/8, комментарии 5/7, бонус 2 балла (сдал третьим).
