### ISSUE TITLE
Некрасов Дмитрий, 2538

### ISSUE THREAD

**Issue by pokrasko** [itmoasm2015/Homework2#41]

**Comment by pokrasko** [comment]
2538/Nekrasov

**Comment by imihajlow** [comment]
```
g++: error: ../Homework2/2538/Nekrasov/libhw.a: No such file or directory
```

**Comment by pokrasko** [comment]
Исправил.

**Comment by imihajlow** [comment]
`libhw.a` должен файл называться.

**Comment by pokrasko** [comment]
Исправил.

**Comment by imihajlow** [comment]
```
and rsi, 0x00000000FFFFFFFF
```

У `and` и подобных ей инструкций не бывает 64-битного операнда-константы. Константа 32-битная, а старшие 32 бита дополняются знаком. Значит, в этом случае получится то же самое, что `and rsi, 0xffffffffffffffff` (можете дизассемблировать и убедиться). Такая конструкция у вас встречается во многих местах, что может привести к ошибке, несмотря на то, что мои тесты успешно пройдены.

**Comment by pokrasko** [comment]
Это нужно исправлять или нет?

Понедельник, 15 июня 2015, 13:50 -07:00 от Ivan Mikhaylov notifications@github.com:

**Comment by imihajlow** [comment]
Да, нужно.

**Comment by pokrasko** [comment]
Исправил.

**Comment by imihajlow** [comment]
Код 7, комментарии 7.
