### ISSUE TITLE
Kaтунина Евгения, 2536, 2536/Katunina

### ISSUE THREAD

**Issue by EvgeniyaKatunina** [itmoasm2015/Homework2#46]

**Comment by imihajlow** [comment]
```
make[1]: nasm: Command not found
make[1]: *** [hw2.o] Error 127
```

**Comment by EvgeniyaKatunina** [comment]
Установлен ли у Вас nasm?

**Comment by imihajlow** [comment]
Ладно, насм так насм.

segfault при заполнении матрицы с помощью matrixSet.

**Comment by EvgeniyaKatunina** [comment]
Вроде исправлено.

**Comment by imihajlow** [comment]
Так как у вас там AVX, выровняйте, пожалуйста, стек перед вызовами функций.

**Comment by EvgeniyaKatunina** [comment]
AVX-инструкций, обращающихся к стеку, у меня нет. Нужен выровненный стек перед каждым coll'ом?

**Comment by imihajlow** [comment]
Да, перед каждым вызовом внешней функции. Иначе я не могу протестировать программу.

**Comment by EvgeniyaKatunina** [comment]
Исправлено.

**Comment by imihajlow** [comment]
В matrixSet опять segfault.

**Comment by EvgeniyaKatunina** [comment]
В каком случае возникает segfault?

**Comment by imihajlow** [comment]
Матрица 20x40, запись в (2, 0).

**Comment by EvgeniyaKatunina** [comment]
Fixed.

**Comment by imihajlow** [comment]
matrixScale не работает (результат неверный).

**Comment by EvgeniyaKatunina** [comment]
Не подскажете ли, почему литерал типа float при передаче в C-шную функцию конвертируется в double? Если вызывать matrixScale() с литералом, она работает корректно. Если же передать литерал в C-шную функцию и из неё вызвать matrixScale(), то в xmm0 будет лежать double, и результат будет некорректным.

**Comment by EvgeniyaKatunina** [comment]
Cо своим вопросом разобралась. Проблема в matrixScale пока не найдена.

**Comment by EvgeniyaKatunina** [comment]
На каких матрице, множителе неверный результат matrixScale()? На моих тестах работает.

**Comment by imihajlow** [comment]
Матрица 20x40, заполнена так: `matrixSet(m, r, c, r * 1000 + c)`, ошибка при проверке:

```
Matrix scaled = matrixScale(m, k);
assert(scaled);
for (int r = 0; r < rows; ++r)
  for (int c = 0; c < cols; ++c) {
    cerr << r << " " << c << endl;
    assert(eq(matrixGet(m,r,c) * k, matrixGet(scaled,r,c)));
}
```

r=0, c=1, matrixGet(scaled, r, c)=0 (не должно быть нуля там).

**Comment by EvgeniyaKatunina** [comment]
Воспроизвела. Выдает корректный ответ. 
Из файла test.c:
void\* m = matrixNew(20,40);
    rows= 20;
    cols = 40;
    for (int r = 0; r < rows; ++r)
      for (int c = 0; c < cols; ++c) {
        matrixSet(m, r, c, r \* 1000 + c);// ошибка при проверке:
    }
    float k = 1;
    Matrix scaled = matrixScale(m, k);
    matrixElement = matrixGet(scaled, 0, 1);
    printf("%f\n", matrixElement);
Добавила в репозиторий обновлённый test.c.

**Comment by imihajlow** [comment]
Я поотлаживал вашу программу, проблема оказалась в том, что xmm0 обнуляется во время вызова matrixNew из matrixScale (глубже я не копал, но там, видимо, виноват malloc). Если что, библиотечные функции вполне вправе портить xmm-регистры, потому что по конвенции вызова их сохранять не нужно.

**Comment by EvgeniyaKatunina** [comment]
Исправлено.

**Comment by imihajlow** [comment]
Теперь ошибка со сложением. Не всегда возникает, но у меня на размере 23х40 в ячейке (22,16) стабильно. Там ноль вместо правильной суммы.

**Comment by EvgeniyaKatunina** [comment]
Исправила.

**Comment by imihajlow** [comment]
Код 7, комметарии 6, бонус 4 за AVX.
