### ISSUE TITLE
Rozhdestvensky Pavel, 2536

### ISSUE THREAD

**Issue by PaulChristmas** [itmoasm2015/Homework2#49]

**Comment by imihajlow** [comment]
segfault при умножении (23x41) на (41x43)

**Comment by PaulChristmas** [comment]
вроде исправил

**Comment by imihajlow** [comment]
Нет. Может быть, забыли коммит?

**Comment by PaulChristmas** [comment]
посмотрел гитхабы и нашел там хорошие тесты. подставил свой код и размеры матриц на умножении [23][41] и [41][43], все проходит

**Comment by imihajlow** [comment]
Извиняюсь, мой косяк. У вас падает при сложении матриц несовместимого размера.

**Comment by PaulChristmas** [comment]
поправил

**Comment by imihajlow** [comment]
Код 8, комментарии 7.
