### ISSUE TITLE
Пересадин Илья, 2539

### ISSUE THREAD

**Issue by pva701** [itmoasm2015/Homework2#5]

**Comment by imihajlow** [comment]
Segmentation fault (libhw.asm:66)

**Comment by pva701** [comment]
Воспроизвести не удалось, нашел возможную причину, исправил.

**Comment by imihajlow** [comment]
matrixNew(0,0) падает

**Comment by pva701** [comment]
Нужно поддерживать матрицы, где одна из размерностей 0? Что тогда будет результатом умножения двух матриц (10, 0) (0, 20) ? Можно ли возвращать на запрос создания такой матрицы ноль?

**Comment by imihajlow** [comment]
Очевидно, что результатом такого умножения будет матрица (10, 20), заполненная нулями: 

```
for (int row = 0; row < m1.rows; ++row)
    for (int col = 0; col < m2.cols; ++col) {
        float sum = 0;
        for (int k = 0; k < m1.cols; ++k)
            sum += m1[row, k] * m2[k, col]; // Не выполнится ни разу, если m1.cols == 0
        result[row, col] = sum;
    }
```

**Comment by imihajlow** [comment]
Хотя, с другой стороны, матрицы с нулевой размерностью — это какая-то ерунда. Я лучше уберу этот тест.

**Comment by imihajlow** [comment]
Но segfault у вас остался (при сложении матриц разного размера).

**Comment by pva701** [comment]
Исправил

**Comment by imihajlow** [comment]
Код 7/8, комментарии 7/7. Бонус 2 балла (разделил третье место с Химулей).

То же самое, вместо функции loadAdress эффективнее было бы сделать макрос. К тому же, address с двумя d пишется.
