### ISSUE TITLE
Виноградов Евгений, 2538

### ISSUE THREAD

**Issue by zhenyavinogradov** [itmoasm2015/Homework2#9]
2538/vinogradov

**Comment by imihajlow** [comment]
Не работает. `matrixGetRows` возвращает не то значение, которое было передано для `matrixNew`.

**Comment by zhenyavinogradov** [comment]
У меня не получается воспроизвести. Не знаете, почему так может быть? Может быть, вы не проинклюдили мой include/matrix.h с определением struct Matrix?

**Comment by imihajlow** [comment]
Вообще-то, я не должен был ничего инклюдить, кроме общего `include/matrix.h`. Тест для всех общий: подключается общий заголовочный файл с интерфейсом и конкретная библиотека.
Попробуйте проверить на разных размерах: может быть, ошибка возникает только в каких-нибудь определенных случаях: если размер не кратен четырем, например. Я проверяю все 16 возможных комбинаций кратности четырем строк и столбцов.

**Comment by zhenyavinogradov** [comment]
Поправил.

**Comment by imihajlow** [comment]
Код 8/8, комментарии 7/7.
